# This code's BN structure
#                   NodeE ─────┐
# NodeA ───┐    ┌── NodeD ───── NodeF ─────┐
#       NodeC ──┼──────────────────── NodeH ──success rate
# NodeB ───┘    └── NodeG ──────────────┘
#    NodeJ ── NodeK ───┘

# NodeA - NumTask
cpd_NumTask:
      NodeName: NumTask
      ClassNum: 4
      CPDarray:
            without_Task: [0.25]
            1_task: [0.25]
            2_task: [0.25]
            more_then_2: [0.25]
# NodeB - Robot
cpd_Robot:
      NodeName: Robot
      ClassNum: 2
      CPDarray:
            ST: [0.999]
            MT: [0.001]
# NodeC - Task
cpd_Task: 
      NodeName: Task
      ClassNum: 2
      CPDarray:
            Yes: [0.900, 0.900,  # Yes|(0 task)(ST, MT)
                  0.100, 0.700,  # Yes|(1 task)(ST, MT)
                  0.010, 0.500,
                  0.001, 0.300]
            No:  [0.100, 0.100,  # No|(0 task)(ST, MT)
                  0.900, 0.300,  # No|(1 task)(ST, MT)
                  0.990, 0.500,
                  0.999, 0.700]
      Evidence: ['NumTask', 'Robot']
      Evidence_card: [4, 2]
# NodeD
cpd_Cost:
      NodeName: Cost
      ClassNum: 15
      CPDarray:
            0~3s:             [0.066667, 0.066667]    # (0~3s)(Yes, No) > Cost為0~3s時 任務接受與否的機率
            3~6s:             [0.066666, 0.066666]    # (3~6s)(Yes, No)
            6~9s:             [0.066666, 0.066666]
            9~12s:            [0.066666, 0.066666]
            12~15s:           [0.066666, 0.066666]
            15~18s:           [0.066666, 0.066666]
            18~21s:           [0.066666, 0.066666]
            21~24s:           [0.066666, 0.066666]
            24~27s:           [0.066666, 0.066666]
            27~30s:           [0.066666, 0.066666]
            30~33s:           [0.066666, 0.066666]
            33~36s:           [0.066666, 0.066666]
            36~39s:           [0.066666, 0.066666]
            39~42s:           [0.066666, 0.066666]
            more_then_42s:    [0.066666, 0.066666]
      Evidence: ['Task']
      Evidence_card: [2]
# NodeE - Battery
cpd_Battery:
      NodeName: Battery
      ClassNum: 3
      CPDarray:
            12.6~12.0V: [0.34]
            12.0~11.4V: [0.33] 
            11.4~10.8V: [0.33]

cpd_CostSatisfaction:
      NodeName: CostSatisfaction
      ClassNum: 2
      CPDarray:
            Yes:  [0.90, 0.95, 0.999,      # Yes|(0~3s)(2~3V, 3~4V, 4~5V)
                  0.85, 0.90, 0.95,       # Yes|(3~6s)(2~3V, 3~4V, 4~5V)
                  0.80, 0.85, 0.90,       # Yes|(6~9s)(2~3V, 3~4V, 4~5V)
                  0.75, 0.80, 0.85,
                  0.70, 0.75, 0.80,
                  0.65, 0.70, 0.75,
                  0.60, 0.65, 0.70,
                  0.55, 0.60, 0.65,
                  0.50, 0.55, 0.60,
                  0.45, 0.50, 0.55,
                  0.40, 0.45, 0.50,
                  0.35, 0.40, 0.45,
                  0.30, 0.35, 0.40,
                  0.25, 0.30, 0.35,
                  0.20, 0.25, 0.30]
            No:   [0.10, 0.05, 0.001,     # No|(0~3s)(2~3V, 3~4V, 4~5V)
                  0.15, 0.10, 0.05,       # No|(3~6s)(2~3V, 3~4V, 4~5V)
                  0.20, 0.15, 0.10,
                  0.25, 0.20, 0.15,
                  0.30, 0.25, 0.20,
                  0.35, 0.30, 0.25,
                  0.40, 0.35, 0.30,
                  0.45, 0.40, 0.35,
                  0.50, 0.45, 0.40,
                  0.55, 0.50, 0.45,
                  0.60, 0.55, 0.50,
                  0.65, 0.60, 0.55,
                  0.70, 0.65, 0.60,
                  0.75, 0.70, 0.65,
                  0.80, 0.75, 0.70]
      Evidence: ['Cost', 'Battery']
      Evidence_card: [15, 3]
cpd_Skill:
      NodeName: Skill
      ClassNum: 2
      CPDarray:
            Yes:  [0.999]
            No:   [0.001]
cpd_SkillCond:
      NodeName: SkillCond
      ClassNum: 2
      CPDarray:
            Yes:  [0.800, 0.001]  # 機器人有駕駛能力時，特有功能(定位的準確性、儀器的精度或攝像頭的品質)好與壞的機率
            No:   [0.200, 0.999] # 機器人沒有駕駛能力時，特有功能好與壞的機率
      Evidence: ['Skill']
      Evidence_card: [2]
cpd_AbilitySatisfaction:
      NodeName: AbilitySatisfaction
      ClassNum: 2
      CPDarray:
            Yes:  [0.900, 0.001, 0.500, 0.500]
            No:   [0.100, 0.999, 0.500, 0.500]
      Evidence: ['Task', 'SkillCond']
      Evidence_card: [2, 2]
cpd_Success:
      NodeName: Success
      ClassNum: 2
      CPDarray:
            Yes:  [0.900, 0.010, 0.010, 0.001, 0.001, 0.001, 0.001, 0.001]
            No:   [0.100, 0.990, 0.990, 0.999, 0.999, 0.999, 0.999, 0.999]
      Evidence: ['Task', 'CostSatisfaction', 'AbilitySatisfaction']
      Evidence_card: [2, 2, 2]