# This code's BN structure
#                   NodeE ─────┐
# NodeA ───┐    ┌── NodeD ───── NodeF ─────┐
#       NodeC ──┼──────────────────── NodeH ──success rate
# NodeB ───┘    └── NodeG ──────────────┘
#    NodeJ ── NodeK ───┘

# NodeA - NumTask
cpd_NumTask:
      NodeName: NumTask
      ClassNum: 4
      CPDarray:
            without_Task: [0.49]
            1_task: [0.49]
            2_task: [0.01]
            more_then_2: [0.01]
# NodeB - Robot
cpd_Robot:
      NodeName: Robot
      ClassNum: 2
      CPDarray:
            ST: [0.999]
            MT: [0.001]
# NodeC - Task
cpd_Task: 
      NodeName: Task
      ClassNum: 2
      CPDarray:
            Yes: [0.900, 0.900,  # Yes|(0 task)(ST, MT)
                  0.100, 0.700,  # Yes|(1 task)(ST, MT)
                  0.010, 0.500,
                  0.001, 0.300]
            No:  [0.100, 0.100,  # No|(0 task)(ST, MT)
                  0.900, 0.300,  # No|(1 task)(ST, MT)
                  0.990, 0.500,
                  0.999, 0.700]
      Evidence: ['NumTask', 'Robot']
      Evidence_card: [4, 2]
# NodeD
cpd_Cost:
      NodeName: Cost
      ClassNum: 11
      CPDarray:
            0~2s:             [0.090910, 0.090910]   # (0~3s)(Yes, No) > Cost為0~3s時 任務接受與否的機率
            2~4s:             [0.090909, 0.090909]    # (3~6s)(Yes, No)
            4~6s:             [0.090909, 0.090909]
            6~8s:             [0.090909, 0.090909]
            8~10s:            [0.090909, 0.090909]
            10~12s:           [0.090909, 0.090909]
            12~14s:           [0.090909, 0.090909]
            14~16s:           [0.090909, 0.090909]
            16~18s:           [0.090909, 0.090909]
            18~20s:           [0.090909, 0.090909]
            more_then_20s:    [0.090909, 0.090909]
      Evidence: ['Task']
      Evidence_card: [2]
# NodeE - Battery
cpd_Battery:
      NodeName: Battery
      ClassNum: 3
      CPDarray:
            12.6~12.0V: [0.33334]
            12.0~11.4V: [0.33333] 
            11.4~10.8V: [0.33333]

cpd_CostSatisfaction:
      NodeName: CostSatisfaction
      ClassNum: 2
      CPDarray:
            Yes:  [0.800, 0.900, 0.999,
                  0.750, 0.850, 0.950,
                  0.700, 0.800, 0.900,
                  0.650, 0.750, 0.850,
                  0.600, 0.700, 0.800,
                  0.550, 0.650, 0.750,
                  0.500, 0.600, 0.700,
                  0.450, 0.550, 0.650,
                  0.400, 0.500, 0.60,
                  0.350, 0.450, 0.550,
                  0.300, 0.400, 0.500]
            No:   [0.200, 0.100, 0.001,
                  0.250, 0.150, 0.050,
                  0.300, 0.200, 0.100,
                  0.350, 0.250, 0.150,
                  0.400, 0.300, 0.200,
                  0.450, 0.350, 0.250,
                  0.500, 0.400, 0.300,
                  0.550, 0.450, 0.350,
                  0.600, 0.500, 0.400,
                  0.650, 0.550, 0.450,
                  0.700, 0.600, 0.500]
      Evidence: ['Cost', 'Battery']
      Evidence_card: [11, 3]
cpd_Skill:
      NodeName: Skill
      ClassNum: 2
      CPDarray:
            Yes:  [0.999]
            No:   [0.001]
cpd_SkillCond:
      NodeName: SkillCond
      ClassNum: 2
      CPDarray:
            Yes:  [0.800, 0.001]  # 機器人有駕駛能力時，特有功能(定位的準確性、儀器的精度或攝像頭的品質)好與壞的機率
            No:   [0.200, 0.999] # 機器人沒有駕駛能力時，特有功能好與壞的機率
      Evidence: ['Skill']
      Evidence_card: [2]
cpd_AbilitySatisfaction:
      NodeName: AbilitySatisfaction
      ClassNum: 2
      CPDarray:
            Yes:  [0.900, 0.001, 0.500, 0.500]
            No:   [0.100, 0.999, 0.500, 0.500]
      Evidence: ['Task', 'SkillCond']
      Evidence_card: [2, 2]
cpd_Success:
      NodeName: Success
      ClassNum: 2
      CPDarray:
            Yes:  [0.900, 0.010, 0.010, 0.001, 0.001, 0.001, 0.001, 0.001]
            No:   [0.100, 0.990, 0.990, 0.999, 0.999, 0.999, 0.999, 0.999]
      Evidence: ['Task', 'CostSatisfaction', 'AbilitySatisfaction']
      Evidence_card: [2, 2, 2]